import puppeteer from "puppeteer";
import { formatNotesHtml } from "./notes-formatter.service";

function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Generate a professional PDF from raw markdown notes.
 * Includes Adyapan AI header/footer, page numbers, and professional layout.
 */
export async function generateNotesPdf(
  markdown: string,
  topic: string,
  options?: { difficulty?: string; type?: string }
): Promise<Buffer> {
  const htmlContent = formatNotesHtml(markdown, topic, options);

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const headerTemplate = `
    <div style="
      width: 100%;
      padding: 20px 48px 14px;
      text-align: center;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-bottom: 1.5px solid #e2e8f0;
      margin: 0 48px;
      box-sizing: border-box;
    ">
      <div style="
        font-size: 22px;
        font-weight: 800;
        color: #0f172a;
        letter-spacing: -0.02em;
        margin-bottom: 3px;
      ">Adyapan AI</div>
      <div style="
        font-size: 11px;
        color: #64748b;
        margin-bottom: 8px;
      ">Generated Study Notes</div>
      <div style="
        font-size: 14px;
        font-weight: 700;
        color: #0f172a;
        max-width: 600px;
        margin: 0 auto 4px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      ">${escapeXml(topic)}</div>
      <div style="
        font-size: 10px;
        color: #94a3b8;
      ">${dateStr}</div>
    </div>
  `;

  const footerTemplate = `
    <div style="
      width: 100%;
      padding: 12px 48px;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-top: 1px solid #e2e8f0;
      margin: 0 48px;
      box-sizing: border-box;
    ">
      <div style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 10px;
        color: #94a3b8;
      ">
        <span>Generated by Adyapan AI &middot; www.adyapanai.com</span>
        <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        <span>&copy; ${new Date().getFullYear()} Adyapan AI</span>
      </div>
    </div>
  `;

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    await page.setContent(htmlContent, {
      waitUntil: "networkidle0",
      timeout: 30000,
    });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "110px",
        bottom: "80px",
        left: "0px",
        right: "0px",
      },
      preferCSSPageSize: false,
      timeout: 60000,
    });

    return Buffer.from(pdfBuffer);
  } catch (error: any) {
    console.error(
      "[PDF Generator] Error generating PDF:",
      error?.message || error
    );
    throw new Error(
      `PDF generation failed: ${error?.message || "Unknown error"}`
    );
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore close errors
      }
    }
  }
}

/**
 * Generate a PDF from pre-formatted HTML content.
 * Useful when the HTML has already been formatted by formatNotesHtml.
 */
export async function generatePdfFromHtml(
  htmlContent: string,
  topic: string
): Promise<Buffer> {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const headerTemplate = `
    <div style="
      width: 100%;
      padding: 20px 48px 14px;
      text-align: center;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-bottom: 1.5px solid #e2e8f0;
      margin: 0 48px;
      box-sizing: border-box;
    ">
      <div style="font-size: 22px; font-weight: 800; color: #0f172a; letter-spacing: -0.02em; margin-bottom: 3px;">Adyapan AI</div>
      <div style="font-size: 11px; color: #64748b; margin-bottom: 8px;">Generated Study Notes</div>
      <div style="font-size: 14px; font-weight: 700; color: #0f172a; max-width: 600px; margin: 0 auto 4px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">${escapeXml(topic)}</div>
      <div style="font-size: 10px; color: #94a3b8;">${dateStr}</div>
    </div>
  `;

  const footerTemplate = `
    <div style="
      width: 100%;
      padding: 12px 48px;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-top: 1px solid #e2e8f0;
      margin: 0 48px;
      box-sizing: border-box;
    ">
      <div style="display: flex; justify-content: space-between; align-items: center; font-size: 10px; color: #94a3b8;">
        <span>Generated by Adyapan AI &middot; www.adyapanai.com</span>
        <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        <span>&copy; ${new Date().getFullYear()} Adyapan AI</span>
      </div>
    </div>
  `;

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    await page.setContent(htmlContent, {
      waitUntil: "networkidle0",
      timeout: 30000,
    });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "110px",
        bottom: "80px",
        left: "0px",
        right: "0px",
      },
      preferCSSPageSize: false,
      timeout: 60000,
    });

    return Buffer.from(pdfBuffer);
  } catch (error: any) {
    console.error(
      "[PDF Generator] Error generating PDF from HTML:",
      error?.message || error
    );
    throw new Error(
      `PDF generation failed: ${error?.message || "Unknown error"}`
    );
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore close errors
      }
    }
  }
}
